FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    tzdata \
    git \
    build-essential \
    cmake \
    libopenblas-dev \
    libomp-dev \
    curl \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update && apt-get install -y \
    python3.9 \
    python3.9-dev \
    python3.9-venv \
    && rm -rf /var/lib/apt/lists/*

# Ensure Python 3.9 has pip
RUN python3.9 -m ensurepip --upgrade
RUN python3.9 -m pip install --upgrade pip

# Set Python 3.9 as default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1

# Verify Python version
RUN python3 --version


# This is mandadotry to avoid caching the "git clone" command
ARG commit_hash
RUN echo "Cloning commit: ${commit_hash}" 

RUN git clone https://github.com/mozilla/bugbug.git /app/testbed

# Set working directory
WORKDIR /app/testbed

# Checkout the specific commit
RUN git checkout ${commit_hash}

# This is needed for http_service/requirements.txt to work - it will be re-installed through pip
RUN apt-get remove -y python3-blinker

# Install Python dependencies
RUN grep -q 'ortools==9.1.9490' requirements.txt && sed -i 's/ortools==9.1.9490/ortools==9.2.9972/g' requirements.txt || true
RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install --no-cache-dir -r test-requirements.txt 
RUN pip install --no-cache-dir -r extra-nn-requirements.txt 
RUN pip install --no-cache-dir -r extra-nlp-requirements.txt 
RUN pip install --no-cache-dir -r http_service/requirements.txt
RUN pip install --no-cache-dir -r infra/spawn_pipeline_requirements.txt 


# Build
RUN pip install -e .

# Set the default command
CMD ["python3", "-c", "print('environment is ready')"]
