FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Zurich
WORKDIR /app
RUN apt-get update && apt-get install -y \
    software-properties-common \
    tzdata \
    git \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm@latest

# RUN npm install -g gulp-cli  # already in package.json
RUN npm install -g nyc

ARG commit_hash
RUN echo "Cloning commit: ${commit_hash}"

RUN git clone https://github.com/mozilla/pdf.js.git /app/pdfjs

WORKDIR /app/pdfjs
RUN git checkout ${commit_hash}
RUN npm ci
RUN npx gulp generic

CMD ["node", "-e", "console.log('pdf.js environment is ready')"]
