FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Zurich
WORKDIR /app
RUN apt-get update \
    && apt-get install -y \
        software-properties-common \
        tzdata \
        git \
        build-essential \
        curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm@latest nyc

ARG commit_hash
RUN echo "Cloning commit: ${commit_hash}" \
    && git clone https://github.com/maettuu/pdf.js-sandbox.git /app/testbed

WORKDIR /app/testbed
RUN git checkout ${commit_hash}
RUN PUPPETEER_SKIP_DOWNLOAD=true npm ci  # necessary to skip outdated downloads (for old commits)
RUN npx gulp generic

CMD ["node", "-e", "console.log('environment is ready')"]
